version: '3.8'

services:
  book_shop_app:
    build: .
    container_name: book_shop_app
    depends_on:
      - book_shop_db
    environment:
      - 'SERVER_PORT=8080'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://book_shop_db:5432/book_shop'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=password'
    ports:
      - '8080:8080'
    restart: on-failure

  book_shop_db:
    image: 'postgres:latest'
    container_name: book_shop_db
    environment:
      - 'POSTGRES_DB=book_shop'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    restart: always